name: CI

on: [push, pull_request]

env:
  SDL3_VERSION: 3.1.3

jobs:
  linux:
    name: Rocky Linux
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
    steps:
    - name: Are we really on Rocky Linux?
      run: cat /etc/os-release

    - name: Install dependencies
      run: |
        dnf update -y
        dnf install -y epel-release
        crb enable
        dnf install -y chrpath cmake gcc git ninja-build

    - uses: actions/checkout@v4
      with:
        submodules: true

    # This can be replaced by installing libsdl once Ubuntu ships SDL3
    - name: Clone SDL3
      run: git clone --depth 1 --branch preview-$SDL3_VERSION https://github.com/libsdl-org/SDL.git

    - name: Build SDL3 (Debug)
      run: |
        cd SDL
        cmake -B debug -G Ninja . -DCMAKE_BUILD_TYPE=Debug
        ninja -C debug
        cd ..

    - name: CMake configure (Debug)
      run: cmake -B debug -G Ninja . -DCMAKE_BUILD_TYPE=Debug -DSDL3_DIR=${GITHUB_WORKSPACE}/SDL/debug

    - name: Build (Debug)
      run: ninja -C debug

    - name: CMake configure (Release)
      run: cmake -B release -G Ninja . -DCMAKE_BUILD_TYPE=Release -DSDL3_DIR=${GITHUB_WORKSPACE}/SDL/debug

    - name: Build (Release)
      run: |
        ninja -C release
        chrpath -d release/libWellspring.so.1
        strip -S release/libWellspring.so.1

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: Wellspring-lib64
        path: release/libWellspring.so.1

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release/libWellspring.so.1

  linux-mingw:
    name: Rocky Linux MinGW
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
      - name: Are we really on Rocky Linux?
        run: cat /etc/os-release

      - name: Install dependencies
        run: |
          dnf update -y
          dnf install -y epel-release
          crb enable
          dnf install -y git cmake ninja-build mingw32-gcc mingw64-gcc xz

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download SDL
        run: |
          curl -LO https://github.com/libsdl-org/SDL/releases/download/preview-$SDL3_VERSION/SDL3-devel-$SDL3_VERSION-mingw.tar.xz
          tar -xvf SDL3-devel-$SDL3_VERSION-mingw.tar.xz -C ${GITHUB_WORKSPACE}

      - name: CMake configure 64-bit (Release)
        run: mingw64-cmake -B release -G Ninja . -DCMAKE_BUILD_TYPE=Release -DSDL3_DIR=${GITHUB_WORKSPACE}/SDL3-$SDL3_VERSION/cmake

      - name: Build 64-bit (Release)
        run: ninja -C release

      - name: Archive build result 64-bit
        uses: actions/upload-artifact@v4
        with:
          name: Wellspring-x64
          path: release/Wellspring.dll

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/Wellspring.dll

  macos-SDL3:
    name: macOS (CMake) SDL3
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    # This can be replaced by installing libsdl once Ubuntu ships SDL3
    - name: Clone SDL3
      run: git clone --depth 1 --branch preview-$SDL3_VERSION https://github.com/libsdl-org/SDL.git

    - name: Install dependencies
      run: brew install ninja

    - name: Build SDL3 (Release)
      run: |
        cd SDL
        cmake -B release -G Ninja . -DCMAKE_BUILD_TYPE=Release
        ninja -C release
        cd ..

    - name: CMake configure (Debug)
      run: cmake -B debug -G Ninja . -DCMAKE_BUILD_TYPE=Debug -DSDL3_DIR=${GITHUB_WORKSPACE}/SDL/release

    - name: Build (Debug)
      run: ninja -C debug

    - name: CMake configure (Release)
      run: cmake -B release -G Ninja . -DCMAKE_BUILD_TYPE=Release -DSDL3_DIR=${GITHUB_WORKSPACE}/SDL/release

    - name: Build (Release)
      run: ninja -C release

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: Wellspring-osx
        path: release/libWellspring.1.dylib

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release/libWellspring.1.dylib
