name: CI

on: [push, pull_request]

env:
  SDL3_VERSION: 3.1.3

jobs:
  linux:
    name: Rocky Linux
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
    steps:
    - name: Are we really on Rocky Linux?
      run: cat /etc/os-release

    - name: Install dependencies
      run: |
        dnf update -y
        dnf install -y epel-release
        crb enable
        dnf install -y chrpath cmake gcc git ninja-build

    - uses: actions/checkout@v4
      with:
        submodules: true

    # This can be replaced by installing libsdl once Ubuntu ships SDL3
    - name: Clone SDL3
      run: git clone --depth 1 --branch preview-$SDL3_VERSION https://github.com/libsdl-org/SDL.git

    - name: Build SDL3 (Debug)
      run: |
        cd SDL
        cmake -B debug -G Ninja . -DCMAKE_BUILD_TYPE=Debug
        ninja -C debug
        cd ..

    - name: CMake configure (Debug)
      run: cmake -B debug -G Ninja . -DCMAKE_BUILD_TYPE=Debug -DSDL3_DIR=${GITHUB_WORKSPACE}/SDL/debug

    - name: Build (Debug)
      run: ninja -C debug

    - name: CMake configure (Release)
      run: cmake -B release -G Ninja . -DCMAKE_BUILD_TYPE=Release -DSDL3_DIR=${GITHUB_WORKSPACE}/SDL/debug

    - name: Build (Release)
      run: |
        ninja -C release
        chrpath -d release/libWellspring.so.1
        strip -S release/libWellspring.so.1

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: Wellspring-lib64
        path: release/libWellspring.so.1

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release/libWellspring.so.1

  windows-msvc-SDL3:
    name: Windows (MSVC) SDL3
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Cache SDL
      uses: actions/cache@v4
      env:
        cache-name: cache-sdl
      with:
        path: C:\SDL3-${{ env.SDL3_VERSION }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Download SDL if not cached
      run: |
        if (-Not (Test-Path C:\SDL3-${{ env.SDL3_VERSION }}))
        {
            Invoke-WebRequest "https://github.com/libsdl-org/SDL/releases/download/preview-$env:SDL3_VERSION/SDL3-devel-$env:SDL3_VERSION-VC.zip" -OutFile C:\SDL.zip
            Expand-Archive C:\SDL.zip -DestinationPath C:\
        }

    - name: CMake configure (Debug)
      run: |
        $env:LDFLAGS =  "/LIBPATH:C:\SDL3-$env:SDL3_VERSION\lib\x64 "
        cmake -B debug -G "Visual Studio 17 2022" . -DCMAKE_BUILD_TYPE:STRING=Debug `
          -A x64 `
          -DSDL3_DIR="C:\SDL3-$env:SDL3_VERSION\cmake" `

    - name: Build (Debug)
      run: cmake --build debug --config Debug

    - name: CMake configure (Release)
      run: |
        $env:LDFLAGS =  "/LIBPATH:C:\SDL3-$env:SDL3_VERSION\lib\x64 "
        cmake -B release -G "Visual Studio 17 2022" . -DCMAKE_BUILD_TYPE:STRING=Release `
          -A x64 `
          -DSDL3_DIR="C:\SDL3-$env:SDL3_VERSION\cmake" `

    - name: Build (Release)
      run: cmake --build release --config Release

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: Wellspring-msvc-x64
        path: release/Release/Wellspring.dll

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release/Release/Wellspring.dll

  macos:
    name: macOS (CMake)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    # This can be replaced by installing libsdl once Ubuntu ships SDL3
    - name: Clone SDL3
      run: git clone --depth 1 --branch preview-$SDL3_VERSION https://github.com/libsdl-org/SDL.git

    - name: Install dependencies
      run: brew install ninja

    - name: Build SDL3 (Debug)
      run: |
        cd SDL
        cmake -B debug -G Ninja . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0
        ninja -C debug
        cd ..

    - name: CMake configure (Debug)
      run: cmake -B debug -G Ninja . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DSDL3_DIR=${GITHUB_WORKSPACE}/SDL/debug

    - name: Build (Debug)
      run: ninja -C debug

    - name: CMake configure (Release)
      run: cmake -B release -G Ninja . -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DSDL3_DIR=${GITHUB_WORKSPACE}/SDL/debug

    - name: Build (Release)
      run: ninja -C release

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: Wellspring-osx
        path: release/libWellspring.1.dylib

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release/libWellspring.1.dylib
